Repository dpgaspar/Flask-AppBuilder, pull requests merged in 2019-11, with the labels that each got.

#1158 New, Show widget template: Add some basic blocks
  docs/templates.rst
  flask_appbuilder/templates/appbuilder/general/widgets/show.html
Labels: enhancement, pending

#1197 [api] Fix, openapi spec for the info endpoint
  flask_appbuilder/api/schemas.py
Labels: api, bug

#1193 [security] Fix, authentication error when using oracle dialect
  flask_appbuilder/security/sqla/manager.py
Labels: bug
