Repository dpgaspar/Flask-AppBuilder, pull requests merged in 2019-05, with the labels that each got.

#966 Fix: change the default email value for auth_remote_user in security manager
  flask_appbuilder/security/manager.py
Labels: bug

#976 Dependency Bump - Previous 0.1.0 version pinned here had an invalid character in its name
  requirements.txt
  setup.py
Labels: dependency-bump, pending

#985 [mvc-api] Fix, deprecation warning version
  docs/quickhowto.rst
  flask_appbuilder/views.py
Labels: bug

#977 New, Bumping Flask-SQLAlchemy version
  requirements.txt
  setup.py
Labels: dependency-bump

#999 Fix, Update minimum required python version for 2.1.1 in Doc/Instalation
  docs/installation.rst
Labels: docs

#1001 docs: fix previous_permission_name- > previous_class_permission_name
  docs/security.rst
  flask_appbuilder/security/manager.py
Labels: docs

#1012 [api] Fix, default resource name must be lower case
  flask_appbuilder/api/__init__.py
Labels: bug

#1007 [api] New, support custom property fields
  flask_appbuilder/api/convert.py
  flask_appbuilder/models/sqla/interface.py
  flask_appbuilder/tests/sqla/models.py
  flask_appbuilder/tests/test_api.py
Labels: enhancement

#1002 [security] Fix, permission mapping
  docs/security.rst
  examples/crud_rest_api/config.py
  flask_appbuilder/actions.py
  flask_appbuilder/api/__init__.py
  flask_appbuilder/baseviews.py
  flask_appbuilder/const.py
  flask_appbuilder/filters.py
  flask_appbuilder/security/manager.py
  flask_appbuilder/security/sqla/manager.py
  flask_appbuilder/tests/test_api.py
  flask_appbuilder/tests/test_base.py
  flask_appbuilder/views.py
Labels: bug

#1010 New: Adds sqlalchemy_utils.types.uuid.UUIDType support to String fields
  flask_appbuilder/models/sqla/interface.py
  requirements.txt
  setup.py
Labels: pending
