Repository dpgaspar/Flask-AppBuilder, pull requests merged in 2020-02, with the labels that each got.

#1242 [security] Set JWT user on flask g
  flask_appbuilder/security/decorators.py
  flask_appbuilder/security/manager.py
Labels: api

#1252 [api] new, override merge openapi docs specs
  examples/crud_rest_api/app/api.py
  flask_appbuilder/api/__init__.py
Labels: api

#1261 [security] Fix, Oauth and OID redirect on auth failure
  flask_appbuilder/security/views.py
Labels: mvc

#1266 Fix, Update version of Flask-Babel to support Werkzeug 1.0
  setup.py
Labels: dependency-bump
